### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by mortiz01** [Naereen/generate-word-cloud.py#2]
Hi! I was hoping to use your script on my computer but I get an error in installation: 

`Collecting generatewordcloud
  Using cached generatewordcloud-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6w/9686gjd9165g9p81scw2z6880000gn/T/pip-build-ZVncRu/generatewordcloud/setup.py", line 19, in <module>
        long_description=''.join(open('README.rst', 'r').readlines()),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6w/9686gjd9165g9p81scw2z6880000gn/T/pip-build-ZVncRu/generatewordcloud/`

Not sure what's going on; pretty sure the dependencies are all installed.

**Comment by Naereen** [comment]
Hi,
OK I reproduced your error, and I know where it comes from.
I'll fix it quickly, before finding a real solution.

**Comment by Naereen** [comment]
Sorry I don't have time to push to pypi, you can instead try this:
```bash
[sudo] pip install git+https://github.com/Naereen/generate-word-cloud.py/
```

**Comment by mortiz01** [comment]
Hi, 
Thanks so much for your quick response! I'll try this out.

**Comment by Naereen** [comment]
Note that the preferred method of installation is *not* with pip, cf. https://github.com/Naereen/generate-word-cloud.py#2-installation

**Comment by Naereen** [comment]
I guess this is solved, I haven't heard from you @mortiz01 since then. Closing :smiley:.
