### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by shokan** [Naereen/generate-word-cloud.py#3]
`pip install generatewordcloud
` gives the following error

> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5l/bkxy55qx31zbyh47t9b76n800000gn/T/pip-install-077022m2/generatewordcloud/

**Comment by Naereen** [comment]
Hi,
Could you give more information please?
System? Environment?

This `/private/var/...` path look weird to me.

**Comment by Naereen** [comment]
Can you instead try this:
```bash
[sudo] pip install git+https://github.com/Naereen/generate-word-cloud.py/
```

**Comment by Naereen** [comment]
(Note that the preferred method of installation is *not* with pip, cf. https://github.com/Naereen/generate-word-cloud.py#2-installation)

**Comment by Naereen** [comment]
@shokan I'm closing, haven't heard from you in a month. Hope you could try and install this project.
